name: serving-api

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Build using Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        cd serving-api/
        pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Run black format
      run: |
        cd serving-api/
        pipenv run isort --check --diff src/ tests/
        pipenv run black --check --diff src/ tests/
    - name: Run pylint
      run: |
        cd serving-api/
        pipenv run pylint --fail-under=7.0 src/ tests/
    - name: Test with pytest
      run: |
        cd serving-api/
        pipenv run pytest